#ifndef _NAVAGRAHA_KUBEENT_DEPLOYMENT_SPEC_H
#define _NAVAGRAHA_KUBEENT_DEPLOYMENT_SPEC_H

namespace navagraha {
namespace kubeent {

extern char DEPLOYMENT_SPEC_MIN_READY_SECONDS[];
extern char DEPLOYMENT_SPCE_PAUSED[];
extern char DEPLOYMENT_SPEC_PROGRESS_DEADLINE_SECONDS[];
extern char DEPLOYMENT_SPEC_REPLICAS[];
extern char DEPLOYMENT_SPEC_REVISION_HISTORY_LIMIT[];
extern char DEPOLYMENT_SPEC_SELECTOR[];
extern char DEPLOYMENT_SPEC_STRATEGT[];
extern char DEPLOYMENT_SPEC_TEMPLATE[];

}
}

#endif
